// Minimal, dependency-free extraction of what SEO and AEO checks need from rendered HTML.
// Regex-based on purpose: the site's HTML is generated by React and well-formed.

const decode = (s = "") =>
  s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#x27;|&#39;/g, "'")
    .replace(/&nbsp;/g, " ");

const attr = (tag, name) => {
  const m = tag.match(new RegExp(`\\s${name}\\s*=\\s*("([^"]*)"|'([^']*)')`, "i"));
  return m ? decode(m[2] ?? m[3]) : null;
};

const text = (html) =>
  decode(
    html
      .replace(/<script[\s\S]*?<\/script>/gi, " ")
      .replace(/<style[\s\S]*?<\/style>/gi, " ")
      .replace(/<[^>]+>/g, " "),
  )
    .replace(/\s+/g, " ")
    .trim();

export function extract(html) {
  const head = html.match(/<head[\s\S]*?<\/head>/i)?.[0] ?? "";
  const main = html.match(/<main[\s\S]*<\/main>/i)?.[0] ?? html;
  const metas = [...head.matchAll(/<meta\b[^>]*>/gi)].map((m) => m[0]);
  const meta = (key) => {
    const tag = metas.find((t) => attr(t, "name") === key || attr(t, "property") === key);
    return tag ? attr(tag, "content") : null;
  };
  const links = [...head.matchAll(/<link\b[^>]*>/gi)].map((m) => m[0]);
  const canonicals = links.filter((l) => attr(l, "rel") === "canonical").map((l) => attr(l, "href"));

  const jsonld = [...html.matchAll(/<script[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/gi)].map(
    (m) => {
      try {
        return { ok: true, data: JSON.parse(m[1]) };
      } catch (e) {
        return { ok: false, error: String(e) };
      }
    },
  );
  const headings = [...main.matchAll(/<(h[1-6])\b[^>]*>([\s\S]*?)<\/\1>/gi)].map((m) => ({
    level: Number(m[1][1]),
    text: text(m[2]),
    hidden: /class="[^"]*visually-hidden/.test(m[0]),
  }));
  const anchors = [...html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)].map((m) => ({
    href: attr(`<a ${m[1]}>`, "href"),
    text: text(m[2]) || attr(`<a ${m[1]}>`, "aria-label") || "",
    rel: attr(`<a ${m[1]}>`, "rel"),
  }));
  const images = [...html.matchAll(/<img\b[^>]*>/gi)].map((m) => ({
    src: attr(m[0], "src"),
    alt: attr(m[0], "alt"),
    hidden: attr(m[0], "aria-hidden") === "true",
    width: attr(m[0], "width"),
    height: attr(m[0], "height"),
  }));
  const buttons = [...main.matchAll(/<button\b([^>]*)>([\s\S]*?)<\/button>/gi)].map((m) => ({
    name: text(m[2]) || attr(`<b ${m[1]}>`, "aria-label") || attr(`<b ${m[1]}>`, "aria-labelledby") || "",
  }));
  const bodyText = text(main);
  return {
    lang: attr(html.match(/<html\b[^>]*>/i)?.[0] ?? "", "lang"),
    title: decode(head.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.trim() ?? "") || null,
    description: meta("description"),
    robots: meta("robots"),
    canonicals,
    og: { title: meta("og:title"), description: meta("og:description"), url: meta("og:url"), image: meta("og:image") },
    twitterCard: meta("twitter:card"),
    jsonld,
    headings,
    anchors,
    images,
    buttons,
    landmarks: ["header", "nav", "main", "footer", "article"].filter((t) => new RegExp(`<${t}\\b`, "i").test(html)),
    times: [...main.matchAll(/<time\b[^>]*datetime="([^"]+)"/gi)].map((m) => m[1]),
    words: bodyText ? bodyText.split(" ").length : 0,
    firstParagraph: text(main.match(/<p\b[^>]*>([\s\S]*?)<\/p>/i)?.[1] ?? ""),
    bodyText,
  };
}

/** Every @graph node (or top-level node) from a page's JSON-LD blocks. */
export function schemaNodes(page) {
  return page.jsonld.flatMap((b) => (b.ok ? (b.data["@graph"] ?? [b.data]) : []));
}
